#Starting FROM
FROM ubuntu:latest

#Taking ARGs
ARG DEBIAN_FRONTEND=noninteractive
#ARG STEAMCMD_INSTALL_PLATFORM="linux"
ARG STEAMCMD_INSTALL_PLATFORM="windows"
ARG STEAM_APP_ID="2278520"
ARG STEAMCMD_PUBLIC_ID="anonymous"

#Define ENVs (hypotheticals)
#ENV ENSHROUDED_GAMEMODE="mygamemode"
#ENV ENSHROUDED_DIFFICULTY="mydifficulty"
#ENV ENSHROUDED_LEVEL_NAME="mymapname"
#ENV ENSHROUDED_SERVER_MOTD="mymotd"
#ENV ENSHROUDED_RCON_PASSWORD="mypassword"

#Execute Base installations instructions
RUN apt update && apt install -y \
vim wget \
&& apt autoclean

#Add repo for steamcmd and install
RUN add-apt-repository -y multiverse && \
dpkg --add-architecture i386 && \
apt update && \
apt install -y wine32 screen lib32gcc-s1 steamcmd

#Create Steam local user
RUN useradd -m steam
WORKDIR /home/steam

#Make symlink & install enshrouded dedicated server
RUN ln -s /usr/games/steamcmd steamcmd && \
./steamcmd +@sSteamCmdForcePlatformType ${STEAMCMD_INSTALL_PLATFORM} +force_install_dir /home/steam/enshrouded +login ${STEAMCMD_PUBLIC_ID} +app_update ${STEAM_APP_ID} +quit

#Add the startupscript and set execution mode
ADD startupscript.sh /home/steam/enshrouded/startupscript.sh
RUN chmod +x /home/steam/enshrouded/startupscript.sh

#Expose ports
#EXPOSE tbd

#Use entrypoint or CMD
ENTRYPOINT [ "/Enshrouded/startupscript.sh" ]
#CMD [ "executable" ]