#Starting FROM
FROM ubuntu:latest

#Taking ARGs
ARG STEAM_APP_ID="2278520"
ARG STEAMCMD_PUBLIC_ID="anonymous"
ARG STEAMCMD_INSTALL_PLATFORM="linux"

#Define ENVs (hypotheticals)
#ENV ENSHROUDED_GAMEMODE="mygamemode"
#ENV ENSHROUDED_DIFFICULTY="mydifficulty"
#ENV ENSHROUDED_LEVEL_NAME="mymapname"
#ENV ENSHROUDED_SERVER_MOTD="mymotd"
#ENV ENSHROUDED_RCON_PASSWORD="mypassword"

#Execute Base installations instructions
RUN apt update && apt install -y \
vim curl steamcmd\
&& apt autoclean

#Create Steam local user
RUN useradd -m steam && \
ln -s /usr/games/steamcmd steamcmd
WORKDIR /home/steam

./steamcmd +@sSteamCmdForcePlatformType linux +login ${STEAMCMD_PUBLIC_ID} +force_install_dir /home/steam/enshrouded +app_update ${STEAM_APP_ID} +quit

#Add the startupscript and set execution mode
ADD startupscript.sh /home/steam/enshrouded/startupscript.sh
RUN chmod +x /home/steam/enshrouded/startupscript.sh

#Expose ports
#EXPOSE tbd

#Use entrypoint or CMD
ENTRYPOINT [ "/Enshrouded/startupscript.sh" ]
#CMD [ "executable" ]