version: '3.9'

services:
  enshrouded:
    image: 'enshrouded:0.1'
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "15636:15636"
      - "15637:15667"
    volumes:
      - "enshrouded_data:/home/steam/enshrouded"

    networks:
      - "backendnetwork"
    environment:
      - "ENSHROUDED_SERVER_NAME=myenshroudedserver"
      - "ENSHROUDED_SERVER_PASSWORD=<insertpasswordhere>"
      - "ENSHROUDED_SERVER_SAVEDIRECTORY=./savegame"
      - "ENSHROUDED_SERVER_LOGDIRECTORY=./logs"
      - "ENSHROUDED_SERVER_MAXPLAYERS=16"

volumes:
  enshrouded_data:

networks:
  backendnetwork:
    attachable: true
